nhse-design-histories:
  title: "NHS England design histories"
  description: "Combined feed for the NHS app, prevention services and referrals and appointments"
  feeds:
    - https://design-history-referrals-app-e8b8c2c8ff86.herokuapp.com/feed.xml
    - https://design-history.nhsapp.service.nhs.uk/feed.xml
    - https://design-history.prevention-services.nhs.uk/feed.xml
